name: "containtername"

services:
  # RabbitMQ
  rabbitmq-master:
    image: rabbitmq:management
    hostname: rabbitmq-m
    environment:
      - "RABBITMQ_ERLANG_COOKIE=secret string"
      - "RABBITMQ_NODENAME=rabbit-master"
      - "RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.config"
    volumes:
      - "./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  # Redis
  redis-1:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "./docker-data/redis-1:/data"
      - "./config/redis/redis-1/redis.conf:/usr/local/etc/redis/redis.conf"

  #Exporter
  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
  # Metrics
  grafana:
    build: env/config/grafana
    ports:
      - "3001:3000"
    volumes:
      - "./docker-data/grafana:/var/lib/grafana"
    environment:
      - "GF_SECURITY_ADMIN_USER=your"
      - "GF_SECURITY_ADMIN_PASSWORD=yourpassword"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./docker-data/prometheus:/prometheus"
    networks:
      - monitoring
  #Postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=catalyst'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '6432:5432'
    restart: unless-stopped
    networks:
      - postgres-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    command: "--log.level=debug"
    environment:
      DATA_SOURCE_URI: "postgres:5432/your?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "secret"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - "./config/postgres/queries.yaml:/etc/postgres_exporter/queries.yaml:ro"
    ports:
      - "9187:9187"
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - postgres

  your-backend:
    image: openjdk:21
    networks:
      catalyst-network:
        ipv4_address: 192.168.0.0
    ports:
      - "8080:8080"
      - "8081:8080"
    volumes:
      - "./your-Web:home/node/Catalyst-Mono"

  your-web:
    image: node:18
    networks:
      catalyst-network:
        ipv4_address: 192.168.0.1
    ports:
      - "3000:3000"
    volumes:
      - "./your-Web:home/node/Catalyst-Web"
  your-reactor:
    image: python:3.11
    networks:
      catalyst-network:
        ipv4_address: 192.168.0.2
    ports:
      - "8082"
    volumes:
      - "./your-Web:home/node/Catalyst-Reactor"

networks:
  catalyst-network:
    name: your-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  postgres-network:
    name: postgres-network
    driver: bridge
  monitoring:
    name: monitoring