server:
  port: 8081
spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  quartz:
    wait-for-jobs-to-complete-on-shutdown: false
  main:
    lazy-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

# noinspection SpringBootApplicationYaml
application:
  version: "@application.version@"
  author: "@application.author@"