scrape_configs:
############ Main ############
  - job_name: 'main'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']


############ Postgres ############
  - job_name: 'postgres'
    static_configs:
      - targets:
        - 'host.docker.internal:9187'


############ Rabbitmq ############
  - job_name: 'rabbitmq'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'host.docker.internal:15692'

############ Redis ############
  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets: [ 'host.docker.internal:9121' ]